#!/usr/bin/env bash

set -ueo pipefail

ASDF_BIN="${ASDF_DIR:-$HOME/.asdf}/bin/"
ASDF_INSTALL_BIN_PATH=$(dirname "$("${ASDF_BIN}/asdf" which asdf-openssl2)")

# TODO: check if you really need custom shims below

regenerate() {
	# After a asdf-openssl2 operation, regenerate asdf-openssl2 shims to find new package binaries
	if "${ASDF_BIN}/asdf" reshim asdf-openssl2; then
		echo "  asdf-openssl2: regenerated shims"
	else
		echo "  asdf-openssl2: failed to regenerate shims"
		exit 1
	fi
	echo
}

trap 'trap - HUP; SIGNAL=SIGHUP; regenerate; kill -HUP $$' HUP
trap 'trap - INT; SIGNAL=SIGINT; regenerate; kill -INT $$' INT
trap 'trap - TERM; SIGNAL=SIGTERM; regenerate; kill -TERM $$' TERM

if "${ASDF_INSTALL_BIN_PATH}/asdf-openssl2" "$@"; then
	case "${1-}" in
		install | develop | uninstall)
			regenerate
			;;
	esac
else
	exit $?
fi
