# These are supported funding model platforms

github: [VadimDor] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: VadimDor # Creator page - Replace with a single Patreon username
open_collective: VadimDor # Replace with a single Open Collective username

ko_fi: [VadimDor] # Replace with a single Ko-fi username
#tidelift: [VadimDor] # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: [VadimDor] # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: [VadimDor] # Replace with a single Liberapay username
issuehunt: [VadimDor] # Replace with a single IssueHunt username
otechie: [VadimDor] # Replace with a single Otechie username

buymeacoffee: [VadimDor]
# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']:
custom:
  [https://VadimDor.github.io/openssl2/donate, 'https://www.buymeacoffee.com/VadimDor']
